### PR TITLE
Change filename and move scope data to config file

### LINKED ISSUE #12: Create config.js file
**Is your feature request related to a problem? Please describe.**
We need a dedicated configuration file to gather all the information the server needs about the environment.

**Describe the solution you'd like**
A file with information about client/server host, github app and auth.

**Describe alternatives you've considered**
For the beginning, we can use a config.js file that imports sensitive information from .env files as, for example, github app client_id, client_secret, callback urls, server host, etc.

**Additional context**
[config.js](https://github.com/calluswhatyouwant/musicritic/blob/master/server/config.js)

**Related**
#1 , #2

### PR DESCRIPTION
**Pull request by fanny**
# Description

This pr, changes `data.js` file of auth folder to `config.js`, is more descriptive.

Fixes #12 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by fanny** [comment]
Yes 👍

**Comment by fanny** [comment]
I will be move for the `arc/`

**Comment by jadsonluan** [comment]
Ok. Should I wait for the change to approve or you will do it after i approve?

**Comment by fanny** [comment]
Done! :smile:

**Pull request merged**
